language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  #fqdn: url.com #uncomment with you have a custom domain
  github-token: $GITHUB_TOKEN  # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master